# Generated by Django 3.0.6 on 2020-10-23 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_personal_details_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
