# Generated by Django 3.0.6 on 2020-10-23 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_personal_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
