# Generated by Django 3.0.6 on 2020-10-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_personal_details_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_Details',
            new_name='Personaldetails',
        ),
    ]
