# Generated by Django 3.0.6 on 2020-10-24 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20201023_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='semester',
            field=models.IntegerField(verbose_name=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
        ),
    ]
