# Generated by Django 3.0.6 on 2020-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20201024_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curr_year',
            field=models.IntegerField(choices=[(1, 'FY'), (2, 'SY'), (3, 'TY'), (4, 'Btech')], default=1),
        ),
    ]
