# Generated by Django 3.0.6 on 2020-10-25 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_student_curr_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curr_sem',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='student',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
