# Generated by Django 3.0.6 on 2020-10-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_criteria_sem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('company', 'branch', 'sem')},
        ),
    ]
