# Generated by Django 3.0.6 on 2020-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20201028_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='verification',
            new_name='status',
        ),
    ]
