# Generated by Django 3.0.6 on 2020-10-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20201031_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlisted',
            name='r_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='', help_text='Enter the post', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Student')),
            ],
        ),
    ]
