# Generated by Django 3.0.6 on 2020-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201031_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
